### ISSUE TITLE
unable to locate jar file after downloading JMeterMySqlBackendListener-master

### ISSUE THREAD

**Issue by athuljose** [KvMadan/JMeterMySqlBackendListener#1]
I am new to this, please let me know how can i progress further. I have downloaded JMeterMySqlBackendListener-master, but i dont see any jar files to provide in my JMeter lib--> Ext folder. Please help

**Comment by KvMadan** [comment]
Download from [releases](https://github.com/KvMadan/JMeterMySqlBackendListener/releases)

**Comment by athuljose** [comment]
Thanks Madan. I am still unable to implement the same. It will be great if you can share any step by step document to complete the setup. Like the tables to create in jmeterdb.

Getting below error:

2019-03-28 10:24:06,552 INFO i.k.j.l.MysqlBackendListenerClient: Sending last metrics
2019-03-28 10:24:06,561 WARN o.a.j.e.StandardJMeterEngine: Error encountered during shutdown of org.apache.jmeter.visualizers.backend.BackendListener@464bd3cc
java.lang.IllegalStateException: Failed calling teardownTest
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:389) ~[ApacheJMeter_components.jar:5.0 r1840935]
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:395) ~[ApacheJMeter_components.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.notifyTestListenersOfEnd(StandardJMeterEngine.java:227) [ApacheJMeter_core.jar:5.0 r1840935]
	at org.apache.jmeter.engine.StandardJMeterEngine.run(StandardJMeterEngine.java:495) [ApacheJMeter_core.jar:5.0 r1840935]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at in.kvm.jmeter.listeners.GenericMysqlMetricsSender.writeEventsToDB(GenericMysqlMetricsSender.java:299) ~[jmetermysql-1.0.jar:?]
	at in.kvm.jmeter.listeners.GenericMysqlMetricsSender.writeAndSendMetrics(GenericMysqlMetricsSender.java:203) ~[jmetermysql-1.0.jar:?]
	at in.kvm.jmeter.listeners.MysqlBackendListenerClient.sendMetrics(MysqlBackendListenerClient.java:306) ~[jmetermysql-1.0.jar:?]
	at in.kvm.jmeter.listeners.MysqlBackendListenerClient.teardownTest(MysqlBackendListenerClient.java:375) ~[jmetermysql-1.0.jar:?]
	at org.apache.jmeter.visualizers.backend.BackendListener.testEnded(BackendListener.java:387) ~[ApacheJMeter_components.jar:5.0 r1840935]
	... 4 more

**Comment by KvMadan** [comment]
@athuljose I suggest to to follow the steps i mentioned in the home page. Make sure you are using the versions of JMeter, sql connector etc as mentioned in it.
